baseURL = 'https://nolagmind.com/'
languageCode = 'en-us'
title = 'No Lag Mind'
theme = 'PaperMod'

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20

[params]
  disableSpecial1stPost = true

[params.analytics]
  google = { id = "G-3E8SE7JMCD" }

[params.homeInfoParams]
  Title = "Learn to work at the speed of thought"
  Content = "Welcome to No Lag Mind - where we explore the intersection of technology, productivity, and human potential."
