baseURL = 'https://nolagmind.com/'
languageCode = 'en-us'
title = 'No Lag Mind'
theme = 'PaperMod'
description = 'Learn to work at the speed of thought - exploring technology, productivity, and human potential.'

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20

[params]
  disableSpecial1stPost = true

[params.label]
  iconSVG = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="13,2 3,14 12,14 11,22 21,10 12,10 13,2"></polygon></svg>'

[params.analytics]
  google = { id = "G-3E8SE7JMCD" }

[params.assets]
  favicon = "favicon.ico"
  favicon16x16 = "favicon-16x16.png"
  favicon32x32 = "favicon-32x32.png"
  apple_touch_icon = "apple-touch-icon.png"
  safari_pinned_tab = "safari-pinned-tab.svg"
  theme_color = "#2e2e33"
  msapplication_TileColor = "#2e2e33"
  og_image = "og-image.png"

[params.social]
  twitter = "nolagmind"
  facebook = "nolagmind"

[params.cover]
  image = "og-image.png"
  relative = false

[params.schema]
  publisherType = "Organization"

[params.homeInfoParams]
  Title = "Learn to work at the speed of thought"
  Content = "Welcome to No Lag Mind - where we explore the intersection of technology, productivity, and human potential."
